# Generated by Django 2.2.3 on 2020-03-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoemCompletion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=20, verbose_name='诗歌上句')),
                ('answer', models.CharField(max_length=20, verbose_name='诗歌下句')),
                ('other1', models.CharField(max_length=20, verbose_name='干扰项1')),
                ('other2', models.CharField(max_length=20, verbose_name='干扰项2')),
                ('other3', models.CharField(max_length=20, verbose_name='干扰项3')),
            ],
            options={
                'verbose_name': '诗歌接龙',
                'verbose_name_plural': '诗歌接龙',
            },
        ),
        migrations.CreateModel(
            name='PoemGenerate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('content', models.CharField(max_length=200, verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '诗歌生成',
                'verbose_name_plural': '诗歌生成',
            },
        ),
    ]
