# Generated by Django 2.2.3 on 2020-05-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poemgenerate',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='生成时间'),
        ),
    ]
