# Generated by Django 2.2.3 on 2020-03-22 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
        ('poetry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Topic', verbose_name='话题')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '关注话题',
                'verbose_name_plural': '关注话题',
                'unique_together': {('user', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='UserFavPoet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('poet', models.ForeignKey(help_text='诗人id', on_delete=django.db.models.deletion.CASCADE, to='poetry.Poet', verbose_name='诗人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '诗人收藏',
                'verbose_name_plural': '诗人收藏',
                'unique_together': {('user', 'poet')},
            },
        ),
        migrations.CreateModel(
            name='UserFavPoem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('poem', models.ForeignKey(help_text='诗歌id', on_delete=django.db.models.deletion.CASCADE, to='poetry.Poem', verbose_name='诗歌')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '诗歌收藏',
                'verbose_name_plural': '诗歌收藏',
                'unique_together': {('user', 'poem')},
            },
        ),
        migrations.CreateModel(
            name='UserFavDynamic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('dynamic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Dynamic', verbose_name='动态')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '关注动态',
                'verbose_name_plural': '关注动态',
                'unique_together': {('user', 'dynamic')},
            },
        ),
        migrations.CreateModel(
            name='StarUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('fans_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fans_user', to=settings.AUTH_USER_MODEL, verbose_name='关注者')),
                ('star_user', models.ForeignKey(help_text='用户id', on_delete=django.db.models.deletion.CASCADE, related_name='star_user', to=settings.AUTH_USER_MODEL, verbose_name='被关注者')),
            ],
            options={
                'verbose_name': '关注用户',
                'verbose_name_plural': '关注用户',
                'unique_together': {('fans_user', 'star_user')},
            },
        ),
    ]
