# Generated by Django 2.2.3 on 2020-03-26 15:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0001_initial'),
        ('community', '0006_remove_dynamiccomment_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFavDynamic',
            new_name='CollectDynamic',
        ),
        migrations.RenameModel(
            old_name='UserFavPoem',
            new_name='CollectPoem',
        ),
        migrations.RenameModel(
            old_name='UserFavPoet',
            new_name='CollectPoet',
        ),
        migrations.RenameModel(
            old_name='UserFavTopic',
            new_name='FollowTopic',
        ),
        migrations.RenameModel(
            old_name='StarUser',
            new_name='FollowUser',
        ),
    ]
