# Generated by Django 2.2.3 on 2020-03-26 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20200326_1557'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowUser',
        ),
    ]
