# Generated by Django 2.2.3 on 2020-03-27 20:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_auto_20200327_2047'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0005_colletcarticle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectdynamic',
            options={'verbose_name': '收藏动态', 'verbose_name_plural': '收藏动态'},
        ),
        migrations.AlterModelOptions(
            name='collectpoem',
            options={'verbose_name': '收藏诗歌', 'verbose_name_plural': '收藏诗歌'},
        ),
        migrations.AlterModelOptions(
            name='collectpoet',
            options={'verbose_name': '收藏诗人', 'verbose_name_plural': '收藏诗人'},
        ),
        migrations.AlterModelOptions(
            name='colletcarticle',
            options={'verbose_name': '收藏文章', 'verbose_name_plural': '收藏文章'},
        ),
        migrations.AlterUniqueTogether(
            name='colletcarticle',
            unique_together={('user', 'article')},
        ),
    ]
