# Generated by Django 2.2.3 on 2020-03-28 19:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0015_auto_20200327_2232'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0006_auto_20200327_2047'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ColletcArticle',
            new_name='CollectArticle',
        ),
    ]
