# Generated by Django 2.2.3 on 2020-04-03 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import operation.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0017_auto_20200403_1157'),
        ('operation', '0007_auto_20200328_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabulousDynamic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('dynamic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Dynamic', verbose_name='动态')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '点赞-动态',
                'verbose_name_plural': '点赞-动态',
                'unique_together': {('user', 'dynamic')},
            },
            bases=(models.Model, operation.models.Base),
        ),
        migrations.CreateModel(
            name='FabulousArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Article', verbose_name='动态')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '收藏文章',
                'verbose_name_plural': '收藏文章',
                'unique_together': {('user', 'article')},
            },
            bases=(models.Model, operation.models.Base),
        ),
    ]
