# Generated by Django 2.2.3 on 2020-04-21 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0031_auto_20200420_0908'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0009_likecomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DislikeComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Comment', verbose_name='评论')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '踩-评论',
                'verbose_name_plural': '踩-评论',
                'unique_together': {('user', 'comment')},
            },
        ),
    ]
