# Generated by Django 2.2.3 on 2020-03-27 21:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200327_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='Avatar/default.png', upload_to='Avatar/%Y/%m/%d/', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='手机'),
        ),
        migrations.AlterField(
            model_name='user',
            name='signature',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='个性签名'),
        ),
    ]
