# Generated by Django 2.2.3 on 2020-04-03 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200327_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.IntegerField(choices=[(1, '秀才'), (2, '举人'), (3, '进士'), (4, '探花'), (5, '榜眼'), (6, '状元')], default=1, verbose_name='称号'),
        ),
        migrations.AddField(
            model_name='user',
            name='integral',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='积分'),
        ),
    ]
