# Generated by Django 2.2.3 on 2020-04-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200403_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='change',
            field=models.IntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别'),
        ),
    ]
