# Generated by Django 2.2.3 on 2020-04-04 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
    ]
