# Generated by Django 2.2.3 on 2020-04-04 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_user_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='change',
            new_name='gender',
        ),
    ]
