# Generated by Django 2.2.3 on 2020-04-07 21:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20200404_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fabulous_num',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='获赞'),
        ),
        migrations.AddField(
            model_name='user',
            name='follower',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='关注'),
        ),
    ]
