# Generated by Django 2.2.3 on 2020-04-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20200407_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_follow',
            field=models.BooleanField(default=False),
        ),
    ]
