# Generated by Django 2.2.3 on 2020-04-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20200421_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fabulous_num',
            field=models.PositiveIntegerField(default=0, verbose_name='获赞'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fans',
            field=models.PositiveIntegerField(default=0, verbose_name='粉丝数'),
        ),
        migrations.AlterField(
            model_name='user',
            name='follower',
            field=models.PositiveIntegerField(default=0, verbose_name='关注'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='integral',
            field=models.PositiveIntegerField(default=0, verbose_name='积分'),
        ),
    ]
