# Generated by Django 2.2.3 on 2020-05-04 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20200504_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_image', models.ImageField(blank=True, max_length=200, upload_to='', verbose_name='卡片背景图片')),
                ('content', models.CharField(max_length=40, verbose_name='内容')),
                ('signature', models.CharField(default='诗词歌赋', max_length=10, verbose_name='落款')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '卡片',
                'verbose_name': '卡片',
            },
        ),
    ]
