# Generated by Django 2.2.3 on 2020-05-04 22:06

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20200504_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='content',
            field=models.CharField(default=user.models._get_default_card_content, max_length=40, verbose_name='内容'),
        ),
    ]
