# Generated by Django 2.2.3 on 2020-05-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20200504_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='Avatar/default.png', max_length=200, upload_to='Avatar/%Y/%m/%d/', verbose_name='头像'),
        ),
    ]
