# Generated by Django 2.2.3 on 2020-05-04 17:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_feedback_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='添加时间'),
            preserve_default=False,
        ),
    ]
