# Generated by Django 2.2.3 on 2020-05-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0007_notification_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='result',
        ),
        migrations.AddField(
            model_name='feedback',
            name='result',
            field=models.SmallIntegerField(choices=[(0, '待处理'), (1, '代办'), (2, '已处理')], default=0, verbose_name='处理结果'),
        ),
    ]
