# Generated by Django 2.2.3 on 2020-05-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0008_auto_20200504_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, max_length=200, upload_to='banner/%Y/%m', verbose_name='轮播图'),
        ),
    ]
