# Generated by Django 2.2.3 on 2020-03-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifycode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsverifycode',
            name='code_type',
            field=models.IntegerField(choices=[(0, '注册'), (1, '找回密码')], default=0, verbose_name='验证码类型'),
        ),
        migrations.AlterField(
            model_name='smsverifycode',
            name='code',
            field=models.CharField(max_length=6, verbose_name='验证码'),
        ),
    ]
