# Generated by Django 2.2.3 on 2020-03-23 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verifycode', '0002_auto_20200322_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailverifycode',
            options={'verbose_name': '邮箱验证码', 'verbose_name_plural': '邮箱验证码'},
        ),
        migrations.AlterModelOptions(
            name='smsverifycode',
            options={'verbose_name': '短信验证码', 'verbose_name_plural': '短信验证码'},
        ),
    ]
