# Generated by Django 2.2.3 on 2020-03-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0004_auto_20200327_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='image',
            field=models.ImageField(blank=True, default='Poem/default.png', upload_to='Poem/%Y/%m/%d/', verbose_name='情景图片'),
        ),
        migrations.AlterField(
            model_name='poet',
            name='image',
            field=models.ImageField(blank=True, default='Poet/default.png', upload_to='Poet/%Y/%m/%d/', verbose_name='肖像'),
        ),
    ]
