# Generated by Django 2.2.3 on 2020-03-27 22:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0005_auto_20200327_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='annotation',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='注解'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='appreciation',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='鉴赏'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='background',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='背景'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='translation',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='译文'),
        ),
        migrations.AlterField(
            model_name='poet',
            name='achievement',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='成就'),
        ),
        migrations.AlterField(
            model_name='poet',
            name='introduce',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='poet',
            name='lifetime',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='生平'),
        ),
    ]
