# Generated by Django 2.2.3 on 2020-03-28 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0006_auto_20200327_2222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mingju',
            options={'verbose_name': '名句', 'verbose_name_plural': '名句'},
        ),
    ]
