# Generated by Django 2.2.3 on 2020-04-03 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0007_auto_20200328_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='click_num',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='浏览量'),
        ),
        migrations.AddField(
            model_name='poet',
            name='click_num',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='浏览量'),
        ),
    ]
