# Generated by Django 2.2.3 on 2020-04-07 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0008_auto_20200403_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mingju',
            name='author',
        ),
    ]
