# Generated by Django 2.2.3 on 2020-04-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0010_auto_20200407_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mingju',
            name='title',
            field=models.CharField(max_length=50, verbose_name='标题'),
        ),
    ]
