# Generated by Django 2.2.3 on 2020-04-07 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0012_taggeditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poem',
            old_name='tags',
            new_name='remark',
        ),
    ]
