# Generated by Django 2.2.3 on 2020-04-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0013_auto_20200407_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='poet',
            name='dy',
            field=models.IntegerField(choices=[(0, '未知'), (1, '唐代'), (2, '宋代'), (3, '元代'), (4, '明代'), (5, '清代'), (6, '先秦'), (7, '两汉'), (8, '魏晋'), (9, '南北朝'), (10, '隋代'), (11, '五代'), (12, '辽朝'), (13, '金朝'), (14, '近代'), (15, '现当代')], default=0, verbose_name='朝代'),
        ),
    ]
