# Generated by Django 2.2.3 on 2020-04-10 08:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('poetry', '0014_poet_dy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taggeditem',
            options={'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
        migrations.AlterField(
            model_name='taggeditem',
            name='tag',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='标签'),
        ),
        migrations.AlterUniqueTogether(
            name='taggeditem',
            unique_together={('tag', 'content_type', 'object_id')},
        ),
    ]
