# Generated by Django 2.2.3 on 2020-04-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0017_auto_20200410_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='is_collect',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='poet',
            name='is_collect',
            field=models.BooleanField(default=False),
        ),
    ]
