# Generated by Django 2.2.3 on 2020-04-20 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0018_auto_20200411_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poet',
            name='click_num',
            field=models.IntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='浏览量'),
        ),
    ]
