# Generated by Django 2.2.3 on 2020-04-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0020_auto_20200420_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='poet',
            name='uuid',
            field=models.CharField(default='1', max_length=32),
        ),
    ]
