# Generated by Django 2.2.3 on 2020-04-21 16:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0021_poet_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poet',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
