# Generated by Django 2.2.3 on 2020-04-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0022_auto_20200421_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='uuid',
            field=models.CharField(default='1', max_length=12),
        ),
    ]
