# Generated by Django 2.2.3 on 2020-04-21 16:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0024_auto_20200421_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
