# Generated by Django 2.2.3 on 2020-04-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0025_auto_20200421_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='click_num',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览量'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='fav_num',
            field=models.PositiveIntegerField(default=0, verbose_name='收藏数'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='image',
            field=models.ImageField(default='Poem/default.png', upload_to='Poem/%Y/%m/%d/', verbose_name='情景图片'),
        ),
        migrations.AlterField(
            model_name='poet',
            name='click_num',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览量'),
        ),
        migrations.AlterField(
            model_name='poet',
            name='fav_num',
            field=models.PositiveIntegerField(default=0, verbose_name='收藏数'),
        ),
        migrations.AlterField(
            model_name='poet',
            name='image',
            field=models.ImageField(default='Poet/default.png', upload_to='Poet/%Y/%m/%d/', verbose_name='肖像'),
        ),
        migrations.AlterField(
            model_name='poet',
            name='work_num',
            field=models.PositiveIntegerField(default=0, verbose_name='收录作品数'),
        ),
    ]
