# Generated by Django 2.2.3 on 2020-04-28 09:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0028_auto_20200428_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='annotation',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='注解'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='appreciation',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='鉴赏'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='background',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='背景'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='translation',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='译文'),
        ),
    ]
