# Generated by Django 2.2.3 on 2020-05-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0030_auto_20200428_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='image',
            field=models.ImageField(default='Poem/default.png', max_length=200, upload_to='Poem/%Y/%m/%d/', verbose_name='情景图片'),
        ),
        migrations.AlterField(
            model_name='poet',
            name='image',
            field=models.ImageField(default='Poet/default.png', max_length=200, upload_to='Poet/%Y/%m/%d/', verbose_name='肖像'),
        ),
    ]
