# Generated by Django 2.2.3 on 2020-05-04 16:00

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poetry', '0031_auto_20200504_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfectPoet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_name', models.CharField(blank=True, max_length=50, verbose_name='别称')),
                ('image', models.ImageField(blank=True, max_length=200, upload_to='Poet/%Y/%m/%d/', verbose_name='肖像')),
                ('born', models.IntegerField(blank=True, null=True, verbose_name='生于')),
                ('death', models.IntegerField(blank=True, null=True, verbose_name='卒于')),
                ('introduce', ckeditor.fields.RichTextField(blank=True, verbose_name='简介')),
                ('lifetime', ckeditor.fields.RichTextField(blank=True, verbose_name='生平')),
                ('achievement', ckeditor.fields.RichTextField(blank=True, verbose_name='成就')),
                ('result', models.SmallIntegerField(choices=[(0, '待处理'), (1, '已完善'), (2, '暂不处理')], default=0, verbose_name='处理结果')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('poet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poetry.Poet', verbose_name='诗人')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '完善诗人信息',
                'verbose_name': '完善诗人信息',
            },
        ),
        migrations.CreateModel(
            name='PerfectPoem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=200, upload_to='Poem/%Y/%m/%d/', verbose_name='情景图片')),
                ('tag', models.CharField(blank=True, max_length=300, verbose_name='标签')),
                ('background', ckeditor.fields.RichTextField(blank=True, verbose_name='背景')),
                ('appreciation', ckeditor.fields.RichTextField(blank=True, verbose_name='鉴赏')),
                ('annotation', ckeditor.fields.RichTextField(blank=True, verbose_name='注解')),
                ('translation', ckeditor.fields.RichTextField(blank=True, verbose_name='译文')),
                ('result', models.SmallIntegerField(choices=[(0, '待处理'), (1, '已完善'), (2, '暂不处理')], default=0, verbose_name='处理结果')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poetry.Poem', verbose_name='诗歌')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '完善诗歌信息',
                'verbose_name': '完善诗歌信息',
            },
        ),
        migrations.CreateModel(
            name='AddPoet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('dynasty', models.IntegerField(choices=[(0, '未知'), (1, '唐代'), (2, '宋代'), (3, '元代'), (4, '明代'), (5, '清代'), (6, '先秦'), (7, '两汉'), (8, '魏晋'), (9, '南北朝'), (10, '隋代'), (11, '五代'), (12, '辽朝'), (13, '金朝'), (14, '近代'), (15, '现当代')], verbose_name='朝代')),
                ('other_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='别称')),
                ('image', models.ImageField(blank=True, max_length=200, upload_to='Poet/%Y/%m/%d/', verbose_name='肖像')),
                ('born', models.IntegerField(blank=True, null=True, verbose_name='生于')),
                ('death', models.IntegerField(blank=True, null=True, verbose_name='卒于')),
                ('introduce', ckeditor.fields.RichTextField(blank=True, verbose_name='简介')),
                ('lifetime', ckeditor.fields.RichTextField(blank=True, verbose_name='生平')),
                ('achievement', ckeditor.fields.RichTextField(blank=True, verbose_name='成就')),
                ('result', models.SmallIntegerField(choices=[(0, '待处理'), (1, '已收录'), (2, '暂不收录')], default=0, verbose_name='处理结果')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '诗人推荐收录',
                'verbose_name': '诗人推荐收录',
            },
        ),
        migrations.CreateModel(
            name='AddPoem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20, verbose_name='作者')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('content', ckeditor.fields.RichTextField(verbose_name='内容')),
                ('image', models.ImageField(blank=True, max_length=200, upload_to='Poem/%Y/%m/%d/', verbose_name='情景图片')),
                ('tag', models.CharField(blank=True, max_length=300, verbose_name='标签')),
                ('background', ckeditor.fields.RichTextField(blank=True, verbose_name='背景')),
                ('appreciation', ckeditor.fields.RichTextField(blank=True, verbose_name='鉴赏')),
                ('annotation', ckeditor.fields.RichTextField(blank=True, verbose_name='注解')),
                ('translation', ckeditor.fields.RichTextField(blank=True, verbose_name='译文')),
                ('result', models.SmallIntegerField(choices=[(0, '待处理'), (1, '已收录'), (2, '暂不收录')], default=0, verbose_name='处理结果')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '诗歌推荐收录',
                'verbose_name': '诗歌推荐收录',
            },
        ),
    ]
