# Generated by Django 2.2.3 on 2020-05-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0032_addpoem_addpoet_perfectpoem_perfectpoet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpoem',
            name='image',
            field=models.ImageField(blank=True, max_length=200, upload_to='Poem/add/%Y/%m/%d/', verbose_name='情景图片'),
        ),
        migrations.AlterField(
            model_name='addpoet',
            name='image',
            field=models.ImageField(blank=True, max_length=200, upload_to='Poet/add/%Y/%m/%d/', verbose_name='肖像'),
        ),
        migrations.AlterField(
            model_name='perfectpoem',
            name='image',
            field=models.ImageField(blank=True, max_length=200, upload_to='Poem/perfect/%Y/%m/%d/', verbose_name='情景图片'),
        ),
        migrations.AlterField(
            model_name='perfectpoet',
            name='image',
            field=models.ImageField(blank=True, max_length=200, upload_to='Poet/perfect/%Y/%m/%d/', verbose_name='肖像'),
        ),
    ]
