# Generated by Django 2.2.3 on 2020-05-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0033_auto_20200505_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpoet',
            name='image',
            field=models.ImageField(default='Poet/default.png', max_length=200, upload_to='Poet/add/%Y/%m/%d/', verbose_name='肖像'),
        ),
    ]
