# Generated by Django 2.2.3 on 2020-05-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0034_auto_20200505_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpoem',
            name='image',
            field=models.ImageField(default='Poem/default.png', max_length=200, upload_to='Poem/add/%Y/%m/%d/', verbose_name='情景图片'),
        ),
    ]
