# Generated by Django 2.2.3 on 2020-05-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0035_auto_20200505_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addpoem',
            name='image',
            field=models.ImageField(blank=True, default='Poem/default.png', max_length=200, upload_to='Poem/add/%Y/%m/%d/', verbose_name='情景图片'),
        ),
        migrations.AlterField(
            model_name='addpoet',
            name='image',
            field=models.ImageField(blank=True, default='Poet/default.png', max_length=200, upload_to='Poet/add/%Y/%m/%d/', verbose_name='肖像'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='image',
            field=models.ImageField(blank=True, default='Poem/default.png', max_length=200, upload_to='Poem/%Y/%m/%d/', verbose_name='情景图片'),
        ),
        migrations.AlterField(
            model_name='poet',
            name='image',
            field=models.ImageField(blank=True, default='Poet/default.png', max_length=200, upload_to='Poet/%Y/%m/%d/', verbose_name='肖像'),
        ),
        migrations.AlterField(
            model_name='poet',
            name='other_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='别称'),
        ),
    ]
