# Generated by Django 2.2.3 on 2020-03-22 15:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=20, unique=True, verbose_name='话题')),
                ('image', models.ImageField(upload_to='Topic/%Y/%m/%d/', verbose_name='图片')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('followed', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='关注人数')),
                ('nums', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='动态数')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '话题',
                'verbose_name_plural': '话题',
            },
        ),
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='upload/%Y/%m/%d')),
            ],
            options={
                'verbose_name': '上传图片',
                'verbose_name_plural': '上传图片',
            },
        ),
        migrations.CreateModel(
            name='Dynamic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30, verbose_name='主题')),
                ('text', models.TextField(verbose_name='动态信息')),
                ('fabulous', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='赞')),
                ('fav_num', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='收藏数')),
                ('comment_num', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='评论数')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.Topic', verbose_name='话题')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户动态',
                'verbose_name_plural': '用户动态',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200, verbose_name='评论内容')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('comment_num', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='评论数')),
                ('deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('dynamic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.Dynamic')),
                ('up', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='superior', to='community.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
    ]
