# Generated by Django 2.2.3 on 2020-03-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dynamic',
            old_name='fabulous',
            new_name='fabulous_num',
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='text',
            field=models.TextField(verbose_name='动态内容'),
        ),
    ]
