# Generated by Django 2.2.3 on 2020-03-22 20:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0002_auto_20200322_1731'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='DynamicComment',
        ),
    ]
