# Generated by Django 2.2.3 on 2020-03-22 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20200322_2008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dynamic',
            options={'verbose_name': '动态', 'verbose_name_plural': '动态'},
        ),
        migrations.RemoveField(
            model_name='dynamiccomment',
            name='deleted',
        ),
    ]
