# Generated by Django 2.2.3 on 2020-03-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20200322_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamiccomment',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
    ]
