# Generated by Django 2.2.3 on 2020-03-25 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_dynamiccomment_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamiccomment',
            name='deleted',
        ),
    ]
