# Generated by Django 2.2.3 on 2020-03-26 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_remove_dynamiccomment_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamic',
            name='deleted',
        ),
    ]
