# Generated by Django 2.2.3 on 2020-03-26 20:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0007_remove_dynamic_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dynamiccomment',
            options={'verbose_name': '动态-评论', 'verbose_name_plural': '动态-评论'},
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, validators=[django.core.validators.MinValueValidator(5)], verbose_name='标题')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('fav_num', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='收藏数')),
                ('comment_num', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='评论数')),
                ('public_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '文章-评论',
                'verbose_name_plural': '文章-评论',
            },
        ),
    ]
