# Generated by Django 2.2.3 on 2020-03-27 22:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0013_auto_20200327_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='动态内容'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='desc',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='描述'),
        ),
    ]
