# Generated by Django 2.2.3 on 2020-03-27 22:32

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0014_auto_20200327_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='动态内容'),
        ),
    ]
