# Generated by Django 2.2.3 on 2020-04-02 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0015_auto_20200327_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='author',
            new_name='user',
        ),
    ]
