# Generated by Django 2.2.3 on 2020-04-03 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0016_auto_20200402_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='click_num',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='浏览量'),
        ),
        migrations.AddField(
            model_name='article',
            name='fabulous_num',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='赞'),
        ),
        migrations.AddField(
            model_name='dynamic',
            name='click_num',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='浏览量'),
        ),
        migrations.AddField(
            model_name='topic',
            name='click_num',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='浏览量'),
        ),
    ]
