# Generated by Django 2.2.3 on 2020-04-03 22:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0018_signin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SignIn',
            new_name='Sign',
        ),
    ]
