# Generated by Django 2.2.3 on 2020-04-07 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0019_auto_20200403_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='public_time',
            new_name='add_time',
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DynamicComment',
        ),
    ]
