# Generated by Django 2.2.3 on 2020-04-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0022_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamic',
            name='is_collect',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dynamic',
            name='is_follow',
            field=models.BooleanField(default=True),
        ),
    ]
