# Generated by Django 2.2.3 on 2020-04-10 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0023_auto_20200410_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dynamic',
            old_name='is_follow',
            new_name='is_fabulous',
        ),
    ]
