# Generated by Django 2.2.3 on 2020-04-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0024_auto_20200410_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamic',
            name='is_fabulous',
            field=models.BooleanField(default=False),
        ),
    ]
