# Generated by Django 2.2.3 on 2020-04-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0025_auto_20200410_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_collect',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='is_fabulous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_follow',
            field=models.BooleanField(default=False),
        ),
    ]
