# Generated by Django 2.2.3 on 2020-04-11 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0026_auto_20200410_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamic',
            name='subject',
        ),
    ]
