# Generated by Django 2.2.3 on 2020-04-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0027_remove_dynamic_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=1000, verbose_name='评论内容'),
        ),
    ]
