# Generated by Django 2.2.3 on 2020-04-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0031_auto_20200420_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_dislike',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_like',
            field=models.BooleanField(default=False),
        ),
    ]
