# Generated by Django 2.2.3 on 2020-04-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0032_auto_20200421_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='uuid',
            field=models.CharField(default='1', max_length=32),
        ),
        migrations.AddField(
            model_name='dynamic',
            name='uuid',
            field=models.CharField(default='1', max_length=32),
        ),
        migrations.AddField(
            model_name='topic',
            name='uuid',
            field=models.CharField(default='1', max_length=32),
        ),
    ]
