# Generated by Django 2.2.3 on 2020-04-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0035_auto_20200421_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(height_field=100, upload_to='uploads/%Y/%m/%d', width_field=200),
        ),
    ]
