# Generated by Django 2.2.3 on 2020-04-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0036_auto_20200428_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d'),
        ),
    ]
