# Generated by Django 2.2.3 on 2020-04-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0037_auto_20200428_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='click_num',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览量'),
        ),
        migrations.AlterField(
            model_name='article',
            name='comment_num',
            field=models.PositiveIntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AlterField(
            model_name='article',
            name='fabulous_num',
            field=models.PositiveIntegerField(default=0, verbose_name='赞'),
        ),
        migrations.AlterField(
            model_name='article',
            name='fav_num',
            field=models.PositiveIntegerField(default=0, verbose_name='收藏数'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_num',
            field=models.PositiveIntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='dislike',
            field=models.PositiveIntegerField(default=0, verbose_name='踩'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='like',
            field=models.PositiveIntegerField(default=0, verbose_name='顶'),
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='click_num',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览量'),
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='comment_num',
            field=models.PositiveIntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='fabulous_num',
            field=models.PositiveIntegerField(default=0, verbose_name='赞'),
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='fav_num',
            field=models.PositiveIntegerField(default=0, verbose_name='收藏数'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='click_num',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览量'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='followed',
            field=models.PositiveIntegerField(default=0, verbose_name='关注人数'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='nums',
            field=models.PositiveIntegerField(default=0, verbose_name='动态数'),
        ),
    ]
