# Generated by Django 2.2.3 on 2020-04-28 09:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0038_auto_20200428_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='desc',
            field=ckeditor.fields.RichTextField(verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(upload_to='Topic/%Y/%m/%d/', verbose_name='图片'),
        ),
    ]
