# Generated by Django 2.2.3 on 2020-05-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0039_auto_20200428_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='comment',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='dynamic',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
    ]
