# Generated by Django 2.2.3 on 2020-05-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0040_auto_20200504_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='deleting',
            field=models.BooleanField(default=False, verbose_name='正在删除'),
        ),
        migrations.AddField(
            model_name='comment',
            name='deleting',
            field=models.BooleanField(default=False, verbose_name='正在删除'),
        ),
        migrations.AddField(
            model_name='dynamic',
            name='deleting',
            field=models.BooleanField(default=False, verbose_name='正在删除'),
        ),
        migrations.AlterField(
            model_name='article',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='已删除'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='已删除'),
        ),
        migrations.AlterField(
            model_name='dynamic',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='已删除'),
        ),
    ]
