# Generated by Django 2.2.3 on 2020-05-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0041_auto_20200504_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(max_length=200, upload_to='Topic/%Y/%m/%d/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(max_length=200, upload_to='uploads/%Y/%m/%d'),
        ),
    ]
